name: Kotlin CI CD with Gradle

on: # Event
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test: # Job id
    runs-on: ubuntu-latest # Runner
    steps:
      - uses: actions/checkout@v2 # Step
      - name: Set up JDK 13
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 13
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "passion-factory-todo" #Must be unique in Heroku
          heroku_email: "sinna94@naver.com"